"""NO8D-control nodes for ComfyUI."""

from .slider_lora_lite import (
    NODE_CLASS_MAPPINGS as _LITE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _LITE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .slider_lora_stack import (
    NODE_CLASS_MAPPINGS as _STACK_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _STACK_NODE_DISPLAY_NAME_MAPPINGS,
)
from .compare_slider_preview import (
    NODE_CLASS_MAPPINGS as _COMPARE_SLIDER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _COMPARE_SLIDER_NODE_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(_LITE_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(_STACK_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(_COMPARE_SLIDER_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(_LITE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(_STACK_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(_COMPARE_SLIDER_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
