"""NO8D controls nodes for ComfyUI."""

from . import prompt_server  # noqa: F401
from .slider_lora_stack import (
    NODE_CLASS_MAPPINGS as _STACK_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _STACK_NODE_DISPLAY_NAME_MAPPINGS,
)
from .compare_slider_preview import (
    NODE_CLASS_MAPPINGS as _COMPARE_SLIDER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _COMPARE_SLIDER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .image_loader import (
    NODE_CLASS_MAPPINGS as _IMAGE_LOADER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _IMAGE_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .prompt_plus import (
    NODE_CLASS_MAPPINGS as _PROMPT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .save_image_text_dataset import (
    NODE_CLASS_MAPPINGS as _SAVE_DATASET_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _SAVE_DATASET_NODE_DISPLAY_NAME_MAPPINGS,
)
from .empty_latent import (
    NODE_CLASS_MAPPINGS as _EMPTY_LATENT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _EMPTY_LATENT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .generate import (
    NODE_CLASS_MAPPINGS as _GENERATE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _GENERATE_NODE_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(_STACK_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(_COMPARE_SLIDER_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(_IMAGE_LOADER_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(_PROMPT_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(_SAVE_DATASET_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(_EMPTY_LATENT_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(_GENERATE_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(_STACK_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(_COMPARE_SLIDER_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(_IMAGE_LOADER_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(_PROMPT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(_SAVE_DATASET_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(_EMPTY_LATENT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(_GENERATE_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
